// Cadastro de disciplinas do Planejador Acadêmico.
// Não altere os dados sem conferir o currículo oficial.

// Ajustes de exibição e atalhos de pesquisa específicos do currículo de Farmácia.
// Os dados das disciplinas abaixo permanecem separados desta configuração para evitar
// misturar lógica de interface com dados curriculares.
const disciplinaAjustes = {
  "FFW361": " (Agentes infecciosos)",
  "FFW362": " (Imunologia)",
  "FFW471": " (Cardio / Renal)",
  "FFW472": " (Endócrino)",
  "FFW481": " (Neurologia)",
  "FFW591": " (Parasitologia)",
  "FFW502": " (Oncologia)"
};

const aliasesPesquisaDisciplinas = {
  "orgexp": "quimica organica experimental",
  "f1": "farmacocinetica e farmacodinamica",
  "exp": "experimental",
  "cif": "cuidado integrado em farmacia",
  "pcq": "producao e controle de qualidade",
  "bqm": "bioquimica",
  "qfm": "quimica farmaceutica",
  "fisqui": "fisico-quimica"
};

const disciplinas = [
  {"periodo":"1","codigo":"BMW103","nome":"Bases Morfológicas Aplicadas à Farmácia","pre":"","co":"","cred":6,"ch":105},
  {"periodo":"1","codigo":"BQM101","nome":"Bioquímica I","pre":"","co":"","cred":3,"ch":45},
  {"periodo":"1","codigo":"FFW111","nome":"Farmacêutico e Sociedade","pre":"","co":"","cred":2,"ch":30},
  {"periodo":"1","codigo":"IQG114","nome":"Química Geral I","pre":"","co":"","cred":4,"ch":60},
  {"periodo":"1","codigo":"MAC108","nome":"Cálculo para Farmácia","pre":"","co":"","cred":3,"ch":45},
  {"periodo":"2","codigo":"BQM103","nome":"Bioquímica II","pre":"BQM101","co":"","cred":3,"ch":45},
  {"periodo":"2","codigo":"IQF235","nome":"Físico-Química I","pre":"MAC108; IQG114","co":"","cred":2,"ch":30},
  {"periodo":"2","codigo":"CFF122","nome":"Fisiologia Humana","pre":"BMW103; BQM101","co":"","cred":6,"ch":90},
  {"periodo":"2","codigo":"FFW121","nome":"Políticas e Planejamento em Saúde Pública","pre":"FFW111","co":"","cred":2,"ch":30},
  {"periodo":"2","codigo":"IQG122","nome":"Química Inorgânica Estrutural FF","pre":"IQG114","co":"","cred":2,"ch":30},
  {"periodo":"2","codigo":"IQO120","nome":"Química Orgânica I","pre":"IQG114","co":"","cred":4,"ch":60},
  {"periodo":"3","codigo":"BMF310","nome":"Farmacocinética e Farmacodinâmica Fundamental","pre":"CFF122","co":"","cred":4,"ch":60},
  {"periodo":"3","codigo":"FFW231","nome":"Farmácia Clínica","pre":"FFW111; CFF122","co":"","cred":2,"ch":30},
  {"periodo":"3","codigo":"FFW232","nome":"Diagnóstico Laboratorial no Cuidado Farmacêutico","pre":"BQM103; CFF122","co":"","cred":2,"ch":30},
  {"periodo":"3","codigo":"IQA123","nome":"Química Analítica Farmacêutica I","pre":"IQG114","co":"","cred":2,"ch":30},
  {"periodo":"3","codigo":"IQF232","nome":"Físico-Química II","pre":"IQF235","co":"","cred":2,"ch":30},
  {"periodo":"3","codigo":"IQO220","nome":"Métodos Espectrométricos","pre":"IQO120","co":"","cred":3,"ch":60},
  {"periodo":"3","codigo":"IQO230","nome":"Química Orgânica II","pre":"IQO120","co":"","cred":4,"ch":60},
  {"periodo":"4","codigo":"FFW241","nome":"Produção e Controle de Qualidade de Produtos Farmacêuticos I (PCQ I)","pre":"IQA123; IQO220","co":"","cred":3,"ch":60},
  {"periodo":"4","codigo":"FFW243","nome":"Métodos Computacionais Aplicados às Ciências Farmacêuticas (MACF)","pre":"BMF310; IQO230","co":"FFW242","cred":1,"ch":30},
  {"periodo":"4","codigo":"FFW242","nome":"Química Farmacêutica e Medicinal I","pre":"BMF310; IQO230","co":"","cred":2,"ch":30},
  {"periodo":"4","codigo":"IQA240","nome":"Química Analítica Farmacêutica Experimental","pre":"IQA123","co":"IQA233","cred":1,"ch":30},
  {"periodo":"4","codigo":"IQA233","nome":"Química Analítica Farmacêutica II","pre":"IQA123","co":"","cred":2,"ch":30},
  {"periodo":"4","codigo":"IQG241","nome":"Química de Coordenações","pre":"IQG122","co":"","cred":2,"ch":30},
  {"periodo":"4","codigo":"IQO242","nome":"Química Orgânica Experimental FF","pre":"IQO230; IQO220","co":"","cred":2,"ch":60},
  {"periodo":"5","codigo":"FFW353","nome":"Gestão e Planejamento da Assistência Farmacêutica","pre":"FFW121","co":"","cred":4,"ch":60},
  {"periodo":"5","codigo":"FFW351","nome":"Toxicologia Geral","pre":"FFW242","co":"","cred":2,"ch":30},
  {"periodo":"5","codigo":"FFW352","nome":"Química Farmacêutica II & Toxicológica","pre":"FFW242; FFW243","co":"FFW351","cred":2,"ch":30},
  {"periodo":"5","codigo":"IMW360","nome":"Microbiologia e Imunologia Fundamental","pre":"CFF122; BQM103","co":"","cred":5,"ch":90},
  {"periodo":"5","codigo":"FFW354","nome":"Produção e Controle de Qualidade de Produtos Farmacêuticos II","pre":"FFW241","co":"","cred":4,"ch":60},
  {"periodo":"5","codigo":"FFW355","nome":"Hematologia F","pre":"FFW232; BMF310","co":"","cred":2,"ch":30},
  {"periodo":"6","codigo":"FFW361","nome":"Cuidado Integrado em Farmácia I","pre":"IMW360; FFW242; FFW231; FFW232","co":"","cred":5,"ch":90},
  {"periodo":"6","codigo":"FFW363","nome":"Farmacobotânica","pre":"BMW103","co":"","cred":1,"ch":30},
  {"periodo":"6","codigo":"FFW362","nome":"Cuidado Integrado em Farmácia II","pre":"IMW360; FFW231; FFW232; FFW242","co":"","cred":4,"ch":60},
  {"periodo":"6","codigo":"FFW364","nome":"Gestão Farmacêutica","pre":"FFW121","co":"","cred":2,"ch":30},
  {"periodo":"6","codigo":"FFW365","nome":"Produção e Controle de Qualidade de Produtos Farmacêuticos III","pre":"FFW241","co":"","cred":3,"ch":45},
  {"periodo":"7","codigo":"FFW471","nome":"Cuidado Integrado em Farmácia III","pre":"FFW242; FFW231; FFW232","co":"","cred":6,"ch":90},
  {"periodo":"7","codigo":"FFW472","nome":"Cuidado Integrado em Farmácia IV","pre":"FFW242; FFW231; FFW232","co":"","cred":4,"ch":60},
  {"periodo":"7","codigo":"FFW473","nome":"Farmacognosia","pre":"IQO242; FFW363","co":"","cred":4,"ch":90},
  {"periodo":"7","codigo":"FFW474","nome":"Produção e Controle de Qualidade de Produtos Farmacêuticos IV","pre":"FFW354; FFW365","co":"","cred":2,"ch":60},
  {"periodo":"8","codigo":"FFW481","nome":"Cuidado Integrado em Farmácia V","pre":"FFW242; FFW231; FFW232","co":"","cred":4,"ch":75},
  {"periodo":"8","codigo":"FFW482","nome":"Farmacoepidemiologia e Bioestatística Aplicada","pre":"FFW121","co":"","cred":3,"ch":45},
  {"periodo":"8","codigo":"FFW483","nome":"Produção e Controle de Qualidade de Produtos Farmacêuticos V","pre":"FFW354; FFW365","co":"","cred":2,"ch":30},
  {"periodo":"8","codigo":"FFW484","nome":"Genética e Biologia Molecular Aplicadas","pre":"BMW103; BQM103","co":"","cred":2,"ch":30},
  {"periodo":"8","codigo":"FFW485","nome":"Biotecnologia Farmacêutica","pre":"IMW360","co":"","cred":2,"ch":30},
  {"periodo":"8","codigo":"FFW486","nome":"Metodologia Científica","pre":"","co":"","cred":2,"ch":30},
  {"periodo":"9","codigo":"FFW591","nome":"Cuidado Integrado em Farmácia VI","pre":"FFW242; FFW231; FFW232","co":"","cred":6,"ch":90},
  {"periodo":"9","codigo":"FFW592","nome":"Processamento e Controle de Qualidade de Alimentos","pre":"IQA233; BQM103","co":"","cred":3,"ch":60},
  {"periodo":"9","codigo":"FFW593","nome":"Produção e Controle de Qualidade de Produtos Farmacêuticos VI","pre":"FFW483","co":"","cred":1,"ch":30},
  {"periodo":"9","codigo":"IEE326","nome":"Economia e Administração de Empresas","pre":"","co":"","cred":3,"ch":45},
  {"periodo":"9","codigo":"FFWK03","nome":"Trabalho de Conclusão de Curso (TCC)","pre":"FFW486","co":"","cred":1,"ch":45},
  {"periodo":"10","codigo":"FFW501","nome":"Farmacoterapia no Cuidado Farmacêutico","pre":"FFW361; FFW362; FFW471; FFW472; FFW481; FFW591","co":"","cred":3,"ch":60},
  {"periodo":"10","codigo":"FFW502","nome":"Cuidado Integrado em Farmácia VII","pre":"FFW242; FFW231; FFW232","co":"","cred":4,"ch":60},
  {"periodo":"10","codigo":"FFW503","nome":"Produção e Controle de Qualidade em Farmácia VII","pre":"FFW473; FFW483","co":"","cred":2,"ch":30},
  {"periodo":"Escolha Condicionada","codigo":"FFM010","nome":"Análise Proteo Apli Diag Terap","pre":"BMW103; BQM103","co":"","cred":2,"ch":30},
  {"periodo":"Escolha Condicionada","codigo":"FFC501","nome":"Bioquímica Clin Experimental","pre":"FFW232","co":"","cred":2,"ch":60},
  {"periodo":"Escolha Condicionada","codigo":"FFC008","nome":"Citopatologia Clinica Aplicada","pre":"FFW232","co":"","cred":3,"ch":60},
  {"periodo":"Escolha Condicionada","codigo":"FFC005","nome":"Hematologia Clínica","pre":"FFW355","co":"","cred":3,"ch":60},
  {"periodo":"Escolha Condicionada","codigo":"FFC009","nome":"Micologia Médica","pre":"FFW591","co":"","cred":3,"ch":60},
  {"periodo":"Escolha Condicionada","codigo":"FFC007","nome":"Microbiologia Clínica Aplicada","pre":"FFW361","co":"","cred":3,"ch":60},
  {"periodo":"Escolha Condicionada","codigo":"FFC004","nome":"Parasitologia Clínica Avançada","pre":"FFW472","co":"","cred":3,"ch":60},
  {"periodo":"Escolha Condicionada","codigo":"FFC003","nome":"Toxico Aplic Análises Clínicas","pre":"IMW360","co":"","cred":3,"ch":60},
  {"periodo":"Escolha Condicionada","codigo":"FFM009","nome":"Bases da Terapêutica Racional","pre":"FFW471","co":"FFW482","cred":2,"ch":30},
  {"periodo":"Escolha Condicionada","codigo":"FFI005","nome":"Bases Mol Doenças Metabólicas","pre":"","co":"","cred":2,"ch":30},
  {"periodo":"Escolha Condicionada","codigo":"FFW003","nome":"Diabetes","pre":"CFF122; BQM103","co":"","cred":3,"ch":45},
  {"periodo":"Escolha Condicionada","codigo":"FFM024","nome":"Farmácia Estética","pre":"FFW483","co":"","cred":2,"ch":30},
  {"periodo":"Escolha Condicionada","codigo":"BMF001","nome":"Farmacologia Clínica","pre":"FFW471","co":"","cred":2,"ch":30},
  {"periodo":"Escolha Condicionada","codigo":"FFM012","nome":"Farmacometria Lab Clínico","pre":"BMF310","co":"","cred":2,"ch":30},
  {"periodo":"Escolha Condicionada","codigo":"FFI019","nome":"Metabol Lipídeos e Obesidade","pre":"BQM103","co":"","cred":2,"ch":30},
  {"periodo":"Escolha Condicionada","codigo":"FFP002","nome":"Téc Aplicações de Injetáveis","pre":"","co":"","cred":2,"ch":45},
  {"periodo":"Escolha Condicionada","codigo":"FFP001","nome":"Técnicas de Socorrismo","pre":"","co":"","cred":2,"ch":45},
  {"periodo":"Escolha Condicionada","codigo":"FFP015","nome":"Bases da Fitoterapia","pre":"FFW473","co":"","cred":4,"ch":60},
  {"periodo":"Escolha Condicionada","codigo":"FFP007","nome":"Botânica Aplicada","pre":"FFW363","co":"","cred":2,"ch":30},
  {"periodo":"Escolha Condicionada","codigo":"FFM413","nome":"Farmacotécnica Homeopática","pre":"FFW354","co":"","cred":3,"ch":60},
  {"periodo":"Escolha Condicionada","codigo":"FFP304","nome":"Introd à Quím de Prod Naturais","pre":"IQO230","co":"","cred":2,"ch":30},
  {"periodo":"Escolha Condicionada","codigo":"FFP004","nome":"Ctrl Micr. Drogas e Alim Orig Veg","pre":"FFW363","co":"","cred":2,"ch":45},
  {"periodo":"Escolha Condicionada","codigo":"FFP016","nome":"Tópicos Especiais em Produtos Naturais","pre":"FFW473","co":"","cred":2,"ch":30},
  {"periodo":"Escolha Condicionada","codigo":"FFI013","nome":"Biocatal Processos Industriais","pre":"BQM103; IQO230","co":"FFI013","cred":2,"ch":30},
  {"periodo":"Escolha Condicionada","codigo":"FFM027","nome":"Cosmetologia","pre":"FFW483","co":"","cred":2,"ch":45},
  {"periodo":"Escolha Condicionada","codigo":"FFM022","nome":"Química Industr Farmacêutica","pre":"IQO230","co":"","cred":3,"ch":45},
  {"periodo":"Escolha Condicionada","codigo":"FFM018","nome":"Téc de Purificação na Ind Farm","pre":"BQM103","co":"FFM018","cred":2,"ch":35},
  {"periodo":"Escolha Condicionada","codigo":"FFM415","nome":"Tecnologia Farmacêutica","pre":"FFW354","co":"","cred":4,"ch":90},
  {"periodo":"Escolha Condicionada","codigo":"FFM026","nome":"Tópicos Especiais em Cromatografia na Indústria Farmacêutica","pre":"FFW241","co":"","cred":1,"ch":30},
  {"periodo":"Escolha Condicionada","codigo":"FFW006","nome":"Tec Prod Hemocomp Hemoderiv","pre":"FFW355","co":"","cred":2,"ch":30},
  {"periodo":"Escolha Condicionada","codigo":"PNN015","nome":"Cromatografia","pre":"IQO230","co":"","cred":3,"ch":60},
  {"periodo":"Escolha Condicionada","codigo":"FFC015","nome":"Análises Forenses","pre":"","co":"","cred":2,"ch":30},
  {"periodo":"Escolha Condicionada","codigo":"FFP008","nome":"Botânica Forense","pre":"FFW353","co":"","cred":2,"ch":30},
  {"periodo":"Escolha Condicionada","codigo":"FFM006","nome":"Téc Mod de Proteína Ap C Farmacêuticas","pre":"IQG114","co":"","cred":2,"ch":30},
  {"periodo":"Escolha Condicionada","codigo":"FFI021","nome":"Empreendedorismo Ciênc Farmac","pre":"","co":"","cred":3,"ch":60},
  {"periodo":"Escolha Condicionada","codigo":"FFW007","nome":"Gestão de Proj e Comport Organiz","pre":"","co":"","cred":2,"ch":30},
  {"periodo":"Escolha Condicionada","codigo":"FFW008","nome":"Gestão Farmacêutica Aplicada","pre":"","co":"","cred":1,"ch":30},
  {"periodo":"Escolha Condicionada","codigo":"FFI010","nome":"Inovação Ciênc Farmacêuticas","pre":"","co":"","cred":3,"ch":45},
  {"periodo":"Escolha Condicionada","codigo":"FFM025","nome":"Patentes Farmacêuticas e Farmoquímicas","pre":"","co":"","cred":2,"ch":30},
  {"periodo":"Escolha Condicionada","codigo":"FFW005","nome":"História Descoberta Fármacos","pre":"","co":"","cred":1,"ch":15},
  {"periodo":"Escolha Condicionada","codigo":"LEB599","nome":"Líng Bras de Sinais","pre":"","co":"","cred":4,"ch":60},
  {"periodo":"Escolha Condicionada","codigo":"NEP148","nome":"Direitos Humanos e Racismo","pre":"","co":"","cred":4,"ch":60},
  {"periodo":"Escolha Condicionada","codigo":"NEP149","nome":"Direitos Humanos e Meio Ambiente","pre":"","co":"","cred":4,"ch":60}
];
